//import localFont from "next/font/local";
//import "./globals.css";
//import { ToastContainer } from 'react-toastify';
//import 'react-toastify/dist/ReactToastify.css'
//import Navbar from "./(dashboard)/Ecommerce/components/Navbar";
//import Footer from "./(dashboard)/Ecommerce/components/Footer";
//import { CartProvider } from "./(dashboard)/context/CartContext";
//import { WishlistProvider } from "./(dashboard)/context/WishlistContext";
//import { SearchProvider } from "./(dashboard)/context/SearchContext";
//import { AuthProvider } from "./(dashboard)/context/AuthContext";
//
////import Signin from "./signin"
////import Admin from "./(dashboard)/admin"
//
//
//const geistSans = localFont({
//  src: "./fonts/GeistVF.woff",
//  variable: "--font-geist-sans",
//  weight: "100 900",
//});
//
//const geistMono = localFont({
//  src: "./fonts/GeistMonoVF.woff",
//  variable: "--font-geist-mono",
//  weight: "100 900",
//});
//
//export const metadata = {
//  title: "AITSERP",
//  description: "Generated by pankaj yadav",
//};
//
//export default function RootLayout({ children }) {
//	 const pathname = usePathname();
//	  const hideLayout =
//    pathname === "/signin" || pathname.startsWith("/admin");
//  return (
//    <html lang="en">
//      <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"></meta>
//    <body
//  className={`${geistSans.variable} ${geistMono.variable} antialiased `}
//>
//  <div className="flex-1 overflow-y-auto  bg-gray-50 dark:bg-gray-900">
//      <AuthProvider>
//			  <WishlistProvider>
//				<CartProvider>
//				  <SearchProvider>
//					  {!hideLayout && <Navbar />}
//					<main>{children}</main>
//					 {!hideLayout && <Footer />}
//				  </SearchProvider>
//				</CartProvider>
//			  </WishlistProvider>
//			</AuthProvider>
//  </div>
//  <ToastContainer />
//</body>
//
//    </html>
//  );
//}
import localFont from "next/font/local";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import Navbar from "./(dashboard)/Ecommerce/components/Navbar";
import Footer from "./(dashboard)/Ecommerce/components/Footer";

import { CartProvider } from "./(dashboard)/context/CartContext";
import { WishlistProvider } from "./(dashboard)/context/WishlistContext";
import { SearchProvider } from "./(dashboard)/context/SearchContext";
import { AuthProvider } from "./(dashboard)/context/AuthContext";

import LayoutWrapper from "./LayoutWrapper"; // ✅ add this

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "AITSERP",
  description: "Generated by pankaj yadav",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <AuthProvider>
          <WishlistProvider>
            <CartProvider>
              <SearchProvider>

                {/* ✅ Use wrapper here */}
                <LayoutWrapper>{children}</LayoutWrapper>

              </SearchProvider>
            </CartProvider>
          </WishlistProvider>
        </AuthProvider>

        <ToastContainer />
      </body>
    </html>
  );
}
